### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by Und3rf10w** [Und3rf10w/OpenJanus#1]
Release the alpha version of the project.

Minimum requirements:

- [x] Text to speech with ElevenLabs' API - #3 
- [x] Persona management via langchain and OpenAI
- [x] Speech to text (whisper?) - #2 
- [x] Onboard IA working (with button keypresses) - #6

**Comment by Und3rf10w** [comment]
Here is an end-to-end demo as of 58a3a8d that shows:

- Speech-to-Text via OpenAI Whisper
- Routing to the correct persona (ATC) via `gpt-4-turbo`
- Stream generation of a reply from the correct persona via `gpt-4-turbo`
- Text-to-Speech of that stream from the persona via ElevenLabs

https://github.com/Und3rf10w/OpenJanus/assets/3812012/bd562214-379b-458c-addb-6844bba1c56a

**Comment by Und3rf10w** [comment]
496a124 is a working concept. Need to do function calling, but it's done.
