### ISSUE TITLE
Pull more parameters into the config

### ISSUE THREAD

**Issue by Und3rf10w** [Und3rf10w/OpenJanus#21]
Need to make more things configurable via the config

# Tasks
- [ ] Which OpenAI model to use for the agents/chains/tools
- [x] Which OpenAI model to use for Whisper STT - 0aacf4e
- [x] Which OpenAI voice to use for Whisper TTS - 4fe54865cd6e333ca6df18a15091a6fdea60605e
  - [ ] Per each chain/tool/agent?
- [x] Path to save recordings and outputs to - 53109da
- [ ] Whether to save recordings and outputs
- [x] Which voice_id to use for ElevenLabs TTS - 21f0ae2
- [x] Voice settings to use for ElevenLabs TTS - 21f0ae2
- [ ] Base URLs via config for integrations
